In [1]:
import pandas as pd

In [14]:
df = pd.read_csv('archive/fixtures.csv')
df

,Match Number,Round Number,Date,Location,Home Team,Away Team,Group,Result
0,2,1,14/09/2021 16:45,Stadion Wankdorf,Young Boys,Man. United,Group F,2 - 1
1,3,1,14/09/2021 16:45,Estadio Ramón Sánchez-Pizjuán,Sevilla,Salzburg,Group G,1 - 1
2,1,1,14/09/2021 19:00,Estadio de la Cerámica,Villarreal,Atalanta,Group F,2 - 2
3,4,1,14/09/2021 19:00,NSC Olimpiyskiy,Dynamo Kyiv,Benfica,Group E,0 - 0
4,5,1,14/09/2021 19:00,Camp Nou,Barcelona,Bayern,Group E,0 - 3
...,...,...,...,...,...,...,...,...
120,121,SF Game 1,26/04/2022 19:00,City of Manchester Stadium,Man. City,Real Madrid,NaN,4 - 3
121,122,SF Game 1,27/04/2022 19:00,Anfield,Liverpool,Villarreal,NaN,2 - 0
122,123,SF Game 2,03/05/2022 19:00,Estadio de la Cerámica,Villarreal,Liverpool,NaN,2 - 3
123,124,SF Game 2,04/05/2022 19:00,Estadio Santiago Bernabéu,Real Madrid,Man. City,NaN,3 - 1
124,125,Final,28/05/2022 19:00,Stade de France,Liverpool,Real Madrid,NaN,0 - 1

In [ ]:
df